# Generated by Django 2.2.4 on 2019-08-31 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190831_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='goto',
        ),
    ]
